/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraprestaciones;

//import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DecimalFormat;
/**
 *
 * @author Anderson
 */
public class GUIPrestaciones extends javax.swing.JFrame {
    int dia;
    int mes;
    int allMes;
    int año;
    double salario;
    double salarioDiario;
    double preaviso;
    double vacaciones;
    double regalia;
    double cesantia;
    int allDias;
    /**
     * Creates new form GUIPrestaciones
     */
    public GUIPrestaciones() {
        initComponents();
    }
    CalculadoraPrestaciones calculadora = new CalculadoraPrestaciones();
    DecimalFormat DF = new DecimalFormat("#.00");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbPrestaciones = new javax.swing.JLabel();
        BtCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LbDiasContables = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        LbPrestaciones1 = new javax.swing.JLabel();
        DCCalendarioEntrada = new com.toedter.calendar.JDateChooser();
        DCCalendarioSalida = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbPagoDiario = new javax.swing.JLabel();
        LbPreaviso = new javax.swing.JLabel();
        LbCesantia = new javax.swing.JLabel();
        LbRegalia = new javax.swing.JLabel();
        LbVacaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        LbPrestaciones.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        LbPrestaciones.setText("  Calculadora de prestaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbPrestaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LbPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));

        BtCalcular.setBackground(new java.awt.Color(0, 153, 255));
        BtCalcular.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        BtCalcular.setText("Calcular");
        BtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(BtCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 91, 150));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tiempo en la empresa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, 30));

        LbDiasContables.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(LbDiasContables, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 360, 50));

        TxtSalario.setText("20000");
        getContentPane().add(TxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, 30));

        LbPrestaciones1.setText("Lbprueba");
        getContentPane().add(LbPrestaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 40));
        getContentPane().add(DCCalendarioEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));
        getContentPane().add(DCCalendarioSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("Entrada:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel3.setText("Salida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ultimo sueldo recibido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        getContentPane().add(LbPagoDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 20));

        LbPreaviso.setText("Su preaviso es de: ");
        getContentPane().add(LbPreaviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        LbCesantia.setText("Su cesantia es de:");
        getContentPane().add(LbCesantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        getContentPane().add(LbRegalia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 230, 30));
        getContentPane().add(LbVacaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void conversor(){
        this.salario = Double.parseDouble(TxtSalario.getText());
        Date fechaEntrada = DCCalendarioEntrada.getDate();
        Date fechaSalida = DCCalendarioSalida.getDate();
        allDias=(int) ((fechaSalida.getTime()-fechaEntrada.getTime())/86400000);
        this.allMes = calculadora.calculoAllMes(allDias);
        this.mes = calculadora.calculoMes(allMes);
        this.regalia = calculadora.regalia(mes, salario);
        this.año = calculadora.calculoAño(allMes);
        this.salarioDiario = calculadora.SalarioDiario(salario);
         this.preaviso = calculadora.pPreaviso(año,mes,salarioDiario);
         this.cesantia = calculadora.cesantia(año, mes, salarioDiario);
         this.vacaciones = calculadora.salarioVacaciones(año, mes, salarioDiario);

    }
    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed
         conversor();

//       -------------------------------------------------------------------------------------------------------------------------------------------
         this.LbDiasContables.setText("EL tiempo que duro en la empresa fue: " + String.valueOf(año) + " años y " + String.valueOf(mes) + " meses ");
         this.LbPreaviso.setText("Su preaviso es de: " + String.valueOf(DF.format(preaviso)));
         this.LbCesantia.setText("Su cesantia es de: " + String.valueOf(DF.format(cesantia)));
         this.LbPagoDiario.setText("Su pago diario es de: " + String.valueOf(DF.format(salarioDiario)));
         this.LbRegalia.setText("Su regalia es de: " + String.valueOf(DF.format(regalia)));
         this.LbVacaciones.setText("Su vaciones es de: " + String.valueOf(DF.format(vacaciones)));
          
        this.LbPrestaciones1.setText("El total es: " + String.valueOf(DF.format(preaviso + cesantia + regalia + vacaciones)));
    }//GEN-LAST:event_BtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrestaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalcular;
    private com.toedter.calendar.JDateChooser DCCalendarioEntrada;
    private com.toedter.calendar.JDateChooser DCCalendarioSalida;
    private javax.swing.JLabel LbCesantia;
    private javax.swing.JLabel LbDiasContables;
    private javax.swing.JLabel LbPagoDiario;
    private javax.swing.JLabel LbPreaviso;
    private javax.swing.JLabel LbPrestaciones;
    private javax.swing.JLabel LbPrestaciones1;
    private javax.swing.JLabel LbRegalia;
    private javax.swing.JLabel LbVacaciones;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
